package config

import "charm.land/catwalk/pkg/catwalk"

const (
	OpenAICodexProviderID   = "openai-codex"
	openAICodexBaseURL      = "https://chatgpt.com/backend-api/codex"
	openAICodexAPIKeyEnv    = "$OPENAI_CODEX_ACCESS_TOKEN"
	openAICodexInstructions = "You are a helpful coding assistant."
)

// OpenAICodexProvider returns the catwalk provider for the OpenAI Codex
// service. Its model catalog mirrors the standard OpenAI provider so users
// can pick from the same set of models regardless of authentication method.
func OpenAICodexProvider() catwalk.Provider {
	models := []catwalk.Model{
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.6-sol",
			Name:               "GPT-5.6 Sol",
			CostPer1MIn:        5,
			CostPer1MOut:       30,
			CostPer1MInCached:  6.25,
			CostPer1MOutCached: 0.5,
			ContextWindow:      1050000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"none", "low", "medium", "high", "xhigh", "max"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.6-terra",
			Name:               "GPT-5.6 Terra",
			CostPer1MIn:        2.5,
			CostPer1MOut:       15,
			CostPer1MInCached:  3.125,
			CostPer1MOutCached: 0.25,
			ContextWindow:      1050000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"none", "low", "medium", "high", "xhigh", "max"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.6-luna",
			Name:               "GPT-5.6 Luna",
			CostPer1MIn:        1,
			CostPer1MOut:       6,
			CostPer1MInCached:  1.25,
			CostPer1MOutCached: 0.1,
			ContextWindow:      1050000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"none", "low", "medium", "high", "xhigh", "max"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.5",
			Name:               "GPT-5.5",
			CostPer1MIn:        5,
			CostPer1MOut:       30,
			CostPer1MInCached:  0.5,
			CostPer1MOutCached: 0,
			ContextWindow:      1050000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"low", "medium", "high", "xhigh"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.5-pro",
			Name:               "GPT-5.5 Pro",
			CostPer1MIn:        30,
			CostPer1MOut:       180,
			CostPer1MInCached:  0,
			CostPer1MOutCached: 0,
			ContextWindow:      1050000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"low", "medium", "high", "xhigh"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.4",
			Name:               "GPT-5.4",
			CostPer1MIn:        2.5,
			CostPer1MOut:       15,
			CostPer1MInCached:  0.25,
			CostPer1MOutCached: 0,
			ContextWindow:      1050000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"low", "medium", "high", "xhigh"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.4-pro",
			Name:               "GPT-5.4 Pro",
			CostPer1MIn:        30,
			CostPer1MOut:       180,
			CostPer1MInCached:  0,
			CostPer1MOutCached: 0,
			ContextWindow:      1050000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"medium", "high", "xhigh"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.4-mini",
			Name:               "GPT-5.4 Mini",
			CostPer1MIn:        0.75,
			CostPer1MOut:       4.5,
			CostPer1MInCached:  0.075,
			CostPer1MOutCached: 0,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"low", "medium", "high", "xhigh"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.4-nano",
			Name:               "GPT-5.4 Nano",
			CostPer1MIn:        0.2,
			CostPer1MOut:       1.25,
			CostPer1MInCached:  0.02,
			CostPer1MOutCached: 0,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"low", "medium", "high", "xhigh"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.3-codex",
			Name:               "GPT-5.3 Codex",
			CostPer1MIn:        1.75,
			CostPer1MOut:       14,
			CostPer1MInCached:  0.175,
			CostPer1MOutCached: 0.175,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"minimal", "low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.2",
			Name:               "GPT-5.2",
			CostPer1MIn:        1.75,
			CostPer1MOut:       14,
			CostPer1MInCached:  0.175,
			CostPer1MOutCached: 0.175,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"minimal", "low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.2-codex",
			Name:               "GPT-5.2 Codex",
			CostPer1MIn:        1.75,
			CostPer1MOut:       14,
			CostPer1MInCached:  0.175,
			CostPer1MOutCached: 0.175,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"minimal", "low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.1",
			Name:               "GPT-5.1",
			CostPer1MIn:        1.25,
			CostPer1MOut:       10,
			CostPer1MInCached:  0.125,
			CostPer1MOutCached: 0.125,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"minimal", "low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.1-codex",
			Name:               "GPT-5.1 Codex",
			CostPer1MIn:        1.25,
			CostPer1MOut:       10,
			CostPer1MInCached:  0.125,
			CostPer1MOutCached: 0.125,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"minimal", "low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.1-codex-max",
			Name:               "GPT-5.1 Codex Max",
			CostPer1MIn:        1.25,
			CostPer1MOut:       10,
			CostPer1MInCached:  0.125,
			CostPer1MOutCached: 0.125,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"minimal", "low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5.1-codex-mini",
			Name:               "GPT-5.1 Codex Mini",
			CostPer1MIn:        0.25,
			CostPer1MOut:       2,
			CostPer1MInCached:  0.025,
			CostPer1MOutCached: 0.025,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5-codex",
			Name:               "GPT-5 Codex",
			CostPer1MIn:        1.25,
			CostPer1MOut:       10,
			CostPer1MInCached:  0.125,
			CostPer1MOutCached: 0.125,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"minimal", "low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5",
			Name:               "GPT-5",
			CostPer1MIn:        1.25,
			CostPer1MOut:       10,
			CostPer1MInCached:  0.125,
			CostPer1MOutCached: 0.125,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"minimal", "low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5-mini",
			Name:               "GPT-5 Mini",
			CostPer1MIn:        0.25,
			CostPer1MOut:       2,
			CostPer1MInCached:  0.025,
			CostPer1MOutCached: 0.025,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-5-nano",
			Name:               "GPT-5 Nano",
			CostPer1MIn:        0.05,
			CostPer1MOut:       0.4,
			CostPer1MInCached:  0.005,
			CostPer1MOutCached: 0.005,
			ContextWindow:      400000,
			DefaultMaxTokens:   128000,
			ReasoningLevels:    []string{"low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "o4-mini",
			Name:               "o4 Mini",
			CostPer1MIn:        1.1,
			CostPer1MOut:       4.4,
			CostPer1MInCached:  0,
			CostPer1MOutCached: 0.275,
			ContextWindow:      200000,
			DefaultMaxTokens:   50000,
			ReasoningLevels:    []string{"low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "o3",
			Name:               "o3",
			CostPer1MIn:        2,
			CostPer1MOut:       8,
			CostPer1MInCached:  0,
			CostPer1MOutCached: 0.5,
			ContextWindow:      200000,
			DefaultMaxTokens:   50000,
			ReasoningLevels:    []string{"low", "medium", "high"},
			DefaultEffort:      "medium",
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-4.1",
			Name:               "GPT-4.1",
			CostPer1MIn:        2,
			CostPer1MOut:       8,
			CostPer1MInCached:  0,
			CostPer1MOutCached: 0.5,
			ContextWindow:      1047576,
			DefaultMaxTokens:   16384,
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-4.1-mini",
			Name:               "GPT-4.1 Mini",
			CostPer1MIn:        0.39999999999999997,
			CostPer1MOut:       1.5999999999999999,
			CostPer1MInCached:  0,
			CostPer1MOutCached: 0.09999999999999999,
			ContextWindow:      1047576,
			DefaultMaxTokens:   16384,
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-4.1-nano",
			Name:               "GPT-4.1 Nano",
			CostPer1MIn:        0.09999999999999999,
			CostPer1MOut:       0.39999999999999997,
			CostPer1MInCached:  0,
			CostPer1MOutCached: 0.024999999999999998,
			ContextWindow:      1047576,
			DefaultMaxTokens:   16384,
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "o3-mini",
			Name:               "o3 Mini",
			CostPer1MIn:        1.1,
			CostPer1MOut:       4.4,
			CostPer1MInCached:  0,
			CostPer1MOutCached: 0.55,
			ContextWindow:      200000,
			DefaultMaxTokens:   50000,
			ReasoningLevels:    []string{"low", "medium", "high"},
			DefaultEffort:      "medium",
			NoAttachments:      true,
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-4o",
			Name:               "GPT-4o",
			CostPer1MIn:        2.5,
			CostPer1MOut:       10,
			CostPer1MInCached:  0,
			CostPer1MOutCached: 1.25,
			ContextWindow:      128000,
			DefaultMaxTokens:   8192,
		}),
		openAICodexModel(openAICodexModelSpec{
			ID:                 "gpt-4o-mini",
			Name:               "GPT-4o-mini",
			CostPer1MIn:        0.15,
			CostPer1MOut:       0.6,
			CostPer1MInCached:  0,
			CostPer1MOutCached: 0.075,
			ContextWindow:      128000,
			DefaultMaxTokens:   8192,
		}),
	}

	return catwalk.Provider{
		ID:                  catwalk.InferenceProvider(OpenAICodexProviderID),
		Name:                "OpenAI Codex (ChatGPT OAuth)",
		APIEndpoint:         openAICodexBaseURL,
		APIKey:              openAICodexAPIKeyEnv,
		Type:                catwalk.TypeOpenAICompat,
		Models:              models,
		DefaultLargeModelID: "gpt-5.6-sol",
		DefaultSmallModelID: "gpt-5.6-luna",
	}
}

// IsOpenAICodexProvider reports whether the provider is the ChatGPT OAuth
// backed Codex provider.
func IsOpenAICodexProvider(providerID string) bool {
	return providerID == OpenAICodexProviderID
}

type openAICodexModelSpec struct {
	ID                 string
	Name               string
	CostPer1MIn        float64
	CostPer1MOut       float64
	CostPer1MInCached  float64
	CostPer1MOutCached float64
	ContextWindow      int64
	DefaultMaxTokens   int64
	ReasoningLevels    []string
	DefaultEffort      string
	NoAttachments      bool
}

func openAICodexModel(spec openAICodexModelSpec) catwalk.Model {
	return catwalk.Model{
		ID:                     spec.ID,
		Name:                   spec.Name,
		CostPer1MIn:            spec.CostPer1MIn,
		CostPer1MOut:           spec.CostPer1MOut,
		CostPer1MInCached:      spec.CostPer1MInCached,
		CostPer1MOutCached:     spec.CostPer1MOutCached,
		ContextWindow:          spec.ContextWindow,
		DefaultMaxTokens:       spec.DefaultMaxTokens,
		CanReason:              len(spec.ReasoningLevels) > 0,
		ReasoningLevels:        spec.ReasoningLevels,
		DefaultReasoningEffort: spec.DefaultEffort,
		SupportsImages:         !spec.NoAttachments,
	}
}
